server:
  port: 7777
  servlet:
    context-path: /web
spring:
  datasource:
    url: jdbc:postgresql://10.68.150.36:5432/postgres?searchPath=dgp_oms_nb
    username: dgp_oms_nb
    password: pAssw0rd
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create # 数据库的操作模式
    properties:
      hibernate:
        default_schema: dgp_oms_nb
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: none
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true
