spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        default_schema: rzpdg
  aop:
    auto: true
    proxy-target-class: true
  datasource:
    sql-script-encoding: utf-8
    username: rzpdg
    password: pass
    url: jdbc:oracle:thin:@192.168.200.230:1521/orcl
    driver-class-name: oracle.jdbc.driver.OracleDriver