spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: public
        temp.use_jdbc_metadata_defaults: false
  aop:
    auto: true
    proxy-target-class: true
  jmx:
    default-domain: root
  datasource:
    sql-script-encoding: utf-8
    username: postgres
    password: pass
    url: jdbc:postgresql://127.0.0.1:5432/hibernate
    driver-class-name: org.postgresql.Driver