server:
  port: 7777
  servlet:
    context-path: /web
spring:
  datasource:
    url: jdbc:postgresql://192.168.200.123:15432/dgpers_dev
    username: dgpers_dev
    password: Passw0rd
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update  # 数据库的操作模式
    properties:
      hibernate:
        default_schema: dgpers_dev
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: update
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true
